name: WFKits
main: WFKits\Main
version: 0.0.1
api: 3.0.0-ALPHA10
load: POSTWORLD
author: David2020xD
description: custom built kits for WitheredFactions
website: https://david202020.github.io/witheredfactions
commands:
 Wizard:
  description: "get a wand"
  usage: "/wizard"
  permission: skeleton.command
permissions:
 skeleton:
  default: true
  description: "perms for WFKits"
  children:
   skeleton.command:
    default: true
    description: "Allows the use of /wizard"
